// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "21c5afd0-9638-4a67-9443-276a6d3d31cd");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.bookmarks.showMobileBookmarks", false);
user_pref("browser.contentblocking.category", "custom");
user_pref("browser.ctrlTab.migrated", true);
user_pref("browser.ctrlTab.recentlyUsedOrder", false);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.fixup.domainwhitelist.privacy", true);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.search.defaultenginename", "DuckDuckGo");
user_pref("browser.search.hiddenOneOffs", "Amazon.com,eBay,Twitter");
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "https://start.parrotlinux.org");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("browser.urlbar.searchSuggestionsChoice", false);
user_pref("browser.urlbar.suggest.searches", false);
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("devtools.onboarding.telemetry.logged", false;
user_pref("distribution.iniFile.exists.appversion", "68.4.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200107212959");
user_pref("extensions.lastAppVersion", "68.4.1");
user_pref("extensions.lastPlatformVersion", "68.4.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.https-everywhere-eff@eff.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-MnnxcxisBPnSXQ@jetpack", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{73a6fe31-595d-460b-a920-fcc0f8843232}", true);
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"017579d0-7f45-443b-af14-b8ffb584652f\",\"formautofill@mozilla.org\":\"a401d10a-93f2-4e62-8ca4-da1a711863d4\",\"fxmonitor@mozilla.org\":\"749fa69f-de4d-4440-8eb6-e61d10a4cadb\",\"webcompat-reporter@mozilla.org\":\"1b195c9e-3ec3-4089-a001-9ba5c09d59fa\",\"webcompat@mozilla.org\":\"a70cb1f1-56bf-4a3d-aa5d-1d76d80a378e\",\"https-everywhere-eff@eff.org\":\"8e660a75-fe7e-4bb1-acb2-84d0eb9b7489\",\"default-theme@mozilla.org\":\"988adf3c-35c0-4c5f-a77a-93786849ce1a\",\"google@search.mozilla.org\":\"db7a708a-d5e0-4009-92cb-928a725e6bfc\",\"amazondotcom@search.mozilla.org\":\"59652ad5-2d55-4ea1-8c88-a43850363cfc\",\"bing@search.mozilla.org\":\"ff064b73-24df-4096-aa6b-50898ec99eb2\",\"ddg@search.mozilla.org\":\"a3121190-8c57-4182-a63c-397a11531229\",\"ebay@search.mozilla.org\":\"e380b053-cad2-4f90-ba1a-9c058a9c53b3\",\"twitter@search.mozilla.org\":\"f47c3fe2-e0ff-4a59-976f-00798877f13d\",\"wikipedia@search.mozilla.org\":\"0b71541b-6d8d-4fd8-919d-4c8862a6a947\",\"{73a6fe31-595d-460b-a920-fcc0f8843232}\":\"5b51acf1-345f-43ed-9ecf-416ab5df21a2\",\"jid1-MnnxcxisBPnSXQ@jetpack\":\"5021499f-5911-4b45-b2dc-1bbfc1d06bed\",\"uBlock0@raymondhill.net\":\"c63c0918-056a-4ac2-8c9c-491eacdb40c4\"}");
user_pref("general.warnOnAboutConfig", false);
user_pref("network.cookie.cookieBehavior", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.blockDotOnion", false);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("network.proxy.autoconfig_url", "file:///etc/anonsurf/onion.pac");
user_pref("network.proxy.socks", "127.0.0.1");
user_pref("network.proxy.socks_port", 9050);
user_pref("network.proxy.type", 2);
user_pref("network.trr.mode", 2);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", false);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1511741576);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("pref.advanced.proxies.disable_button.reload", false);
user_pref("pref.privacy.disable_button.cookie_exceptions", false);
user_pref("pref.privacy.disable_button.tracking_protection_exceptions", false);
user_pref("pref.privacy.disable_button.view_cookies", false);
user_pref("pref.privacy.disable_button.view_passwords", false);
user_pref("pref.privacy.disable_button.view_passwords_exceptions", false);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.history.custom", true);
user_pref("privacy.trackingprotection.cryptomining.enabled", true);
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.fingerprinting.enabled", true);
user_pref("privacy.trackingprotection.introCount", 20);
user_pref("security.disable_button.openCertManager", false);
user_pref("services.sync.clients.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
